---
title: "Met Opera Performers"
output: 
  html_document: 
    keep_md: yes
---

```{r warning=FALSE, message=FALSE}
library(rvest)
library(dplyr)
library(foreach)
library(ggplot2)
library(pastecs)
```

###Read Data

```{r warning=FALSE}
performers<- read_html("https://en.wikipedia.org/wiki/List_of_performers_at_the_Metropolitan_Opera")
names<-performers%>% html_nodes("td") %>% html_nodes("a")%>% html_text()
performers<-performers %>%
html_nodes(xpath='//*[@id="mw-content-text"]/table[1]') %>%
html_table()
performers<-performers[[1]]
```

###Clean Data

Clean and unicode encode names.

Clean categories

```{r warning=FALSE}
# Clean names
rows<-nrow(performers)
len<-length(names)
for(i in 1:rows)
{
  for(j in 1:len)
  {
    if(length(grep(names[j], performers[i,]$Performer))>0)
    {
      # Unicode encode
      Encoding(names[j]) <- "UTF-8"
      performers[i,]$Performer<-names[j]
      break
    }
  }
}

# Clean categories
performers[performers$Category=="Bass-baritone",]$Category<-"Bass-Baritone"
performers[performers$Category=="Mezzo-soprano, Soprano",]$Category<-"Soprano, Mezzo-soprano"
#performers[performers$Category=="Mezzo-soprano",]$Category<-"Mezzo-Soprano"
#performers[performers$Category=="Mezzo Soprano",]$Category<-"Mezzo-Soprano"
```

###Calculate Longevity

```{r warning=FALSE}
performers$"First performance" <- as.Date(performers$"First performance", "%m/%d/%Y")
performers$"Last performance" <- as.Date(performers$"Last performance", "%m/%d/%Y")
performers <- mutate(performers, Longevity = round(daystoyears(unclass(performers$"Last performance")) - daystoyears(unclass(performers$"First performance")), digits=1))
```

###Calculate Performance per Year

```{r warning=FALSE}
performers$Performance.Per.Year <- round(performers$Performance/performers$Longevity, digits = 1)
```

###Maximum Display 25 Performers in a Plot

```{r warning=FALSE}
cats<-unique(performers$Category)
cats
count<-length(cats)
top=25
```

###Ranking by Longevity

```{r warning=FALSE}
foreach(i = 1:count) %do%
{
  cat_performers<-performers[performers$Category==cats[i],]
  cat_performers$Performer<-factor(cat_performers$Performer, levels=cat_performers[order(cat_performers$Longevity), "Performer"])
  
  if(dim(cat_performers)[1] > top)
  {
    cat_performers<-cat_performers[1:top,]
  }
  
  ggplot(data=cat_performers, aes(x=Performer, y=Longevity, fill=Longevity)) + 
    geom_bar(stat="identity") +
    geom_text(data=cat_performers, aes(label=Longevity), size=3, y = cat_performers$Longevity/2, color="white") +
    coord_flip() +
    ggtitle(paste(cats[i], "Ranking by Longevity", sep=" ")) +
    theme(legend.position="none") + 
    labs(y="Longevity (year)")
}
```

###Ranking by Performance

```{r warning=FALSE}
foreach(i = 1:count) %do%
{
  cat_performers<-performers[performers$Category==cats[i],]
  cat_performers$Performer<-factor(cat_performers$Performer, levels=cat_performers[order(cat_performers$Performances), "Performer"])
  
  if(dim(cat_performers)[1] > top)
  {
    cat_performers<-cat_performers[1:top,]
  }
  
  ggplot(data=cat_performers, aes(x=Performer, y=Performances, fill=Performances)) + 
    geom_bar(stat="identity") +
    geom_text(data=cat_performers, aes(label=Performances), size=3, y = cat_performers$Performances/2, color="white") +
    coord_flip() +
    ggtitle(paste(cats[i], "Ranking by Performance", sep=" ")) +
    theme(legend.position="none")
}
```

###Ranking by Average Performance per Year

```{r warning=FALSE}
foreach(i = 1:count) %do%
{
  cat_performers<-performers[performers$Category==cats[i],]
  cat_performers$Performer<-factor(cat_performers$Performer, levels=cat_performers[order(cat_performers$Performance.Per.Year), "Performer"])
  
  if(dim(cat_performers)[1] > top)
  {
    cat_performers<-cat_performers[1:top,]
  }
  
  ggplot(data=cat_performers, aes(x=Performer, y=Performance.Per.Year, fill=Performance.Per.Year)) + 
    geom_bar(stat="identity") +
    geom_text(data=cat_performers, aes(label=Performance.Per.Year), size=3, y = cat_performers$Performance.Per.Year/2, color="white") +
    coord_flip() +
    ggtitle(paste(cats[i], "Ranking by Average Performance per Year", sep=" ")) +
    theme(legend.position="none") + 
    labs(y="Average Performance per Year")
}
```

###Summary of Longevity

```{r warning=FALSE}
groupByCategory <- group_by(performers, Category)
summarise(groupByCategory, Count=n(), MinPerformances=min(Performances), MaxPerformances=max(Performances))
```

###Summary of Performance

```{r warning=FALSE}
summarise(groupByCategory, Count=n(), MinLongevity=min(Longevity), MaxLongevity=max(Longevity))
```

###Summary of Average Performance per Year

```{r warning=FALSE}
summarise(groupByCategory, Count=n(), MinLongevity=min(Performance.Per.Year), MaxLongevity=max(Performance.Per.Year))
```
