---
title: 'Density'
output: 
  html_document: 
    keep_md: yes
---

```{r}
library(datasets)
library(ggplot2)
library(gridExtra)
library(plotly)
```

###geom_boxplot

```{r}
ggplot(data=ToothGrowth, aes(x=as.factor(dose), y=len, fill=as.factor(dose))) +
    geom_boxplot() +   
    facet_grid(. ~ supp) +   
    xlab("Dose (mg)") +
    ylab("Tooth length (mm)") +
    guides(fill=guide_legend(title="Dose")) + 
    ggtitle("Correlation of Tooth Length, \nDose, and Supplement Type")
```

###geom_violin

```{r}
ggplot(data=ToothGrowth, aes(x=as.factor(dose), y=len, fill=as.factor(dose))) +
    geom_violin() +   
    facet_grid(. ~ supp) +   
    xlab("Dose (mg)") +
    ylab("Tooth length (mm)") +
    guides(fill=guide_legend(title="Dose")) + 
    ggtitle("Correlation of Tooth Length, \nDose, and Supplement Type")

ggplot(data=ToothGrowth, aes(x=as.factor(dose), y=len, fill=as.factor(dose))) +
    geom_violin(adjust = .5) +   
    facet_grid(. ~ supp) +   
    xlab("Dose (mg)") +
    ylab("Tooth length (mm)") +
    guides(fill=guide_legend(title="Dose")) + 
    ggtitle("Correlation of Tooth Length, \nDose, and Supplement Type")
```

###geom_density

```{r}
ggplot(ToothGrowth,aes(x=len, fill=as.factor(dose))) +
    geom_density() + 
    facet_grid(dose~supp) +
    xlab("Tooth length (mm)") +
    ylab("Density") +
    guides(fill=guide_legend(title="Dose", reverse=TRUE)) + 
    ggtitle("Correlation of Tooth Length, \nDose, and Supplement Type") + 
    coord_flip()

ggplot(ToothGrowth,aes(x=len, fill=as.factor(dose))) +
    geom_density(adjust = .5) + 
    facet_grid(dose~supp) +
    xlab("Tooth length (mm)") +
    ylab("Density") +
    guides(fill=guide_legend(title="Dose", reverse=TRUE)) + 
    ggtitle("Correlation of Tooth Length, \nDose, and Supplement Type") + 
    coord_flip()

```

###gridExtra

```{r warning=FALSE, message=FALSE}
p <- ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, colour = Species)) + 
    geom_point(aes(alpha = 0.5)) + 
    ggtitle("Correlation of Sepal Length and Width") + 
    theme(legend.position="none")

ggExtra::ggMarginal(p)

ggExtra::ggMarginal(p, type = "histogram")

ggExtra::ggMarginal(p, type = "histogram", size = 2, col = "darkorange4", fill = "gold")

ggExtra::ggMarginal(p, type = "boxplot", col = "navy", fill = "lightslateblue")
```

###ployly

```{r warning=FALSE, message=FALSE}
s <- subplot(
  plot_ly(x = iris$Sepal.Length, type = "histogram"),
  plotly_empty(),
  plot_ly(x = iris$Sepal.Length, y = iris$Sepal.Width, type = "histogram2dcontour"),
  plot_ly(y = iris$Sepal.Width, type = "histogram"),
  nrows = 2, heights = c(0.2, 0.8), widths = c(0.8, 0.2), margin = 0, shareX = TRUE, shareY = TRUE, titleX = FALSE, titleY = FALSE
)
layout(s, showlegend = FALSE)

```